# Linear Algebra

## Vectors

Vectors in geometry are 1-dimensinal arrays of number or functions used to operate on points on line or plane.

Vectors store the magnitude and direction of a potential change to a point.

A vector with more than one dimension is called a matrix.

Vector Notation   v(with array at its head facing rigth) = (v1,v2)

Example : Tis vector says move left 2 units and up 5 units. v=(-2,5)

### Scalar Operations

The simplest vector operation in a scaler operation. It involves one vector an done number. You simply apply the number to all the values in the large vector -- add. subtract, multiply, etc.

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
x + 1

array([2, 3, 4])

### Element-wise Operations

The vector operations below are elementwise. The first value in first vector is matched with the first value in the second vector. The second with the seconf and so on.

This means the vectors MUST have equal dimensions to complete the operation.

There is exception: if one of the vector is of size one it can be treated like a scalar and applied to all the values in the larger vector.

#### Addition

In [4]:
y = np.array([1,2,3])
x = np.array([20,30,40])

In [5]:
y + x

array([21, 32, 43])

#### Subtraction

In [6]:
y = np.array([1,2,3])
x = np.array([20,30,40])

In [7]:
y - x

array([-19, -28, -37])

#### Division

In [8]:
y = np.array([1,2,3]).astype(float)
x = np.array([20,30,40]).astype(float)

In [9]:
y / x

array([0.05      , 0.06666667, 0.075     ])

#### Multiplication -- Dot Product and Hadamard Product

in both cases the inuts must be of equal dimensions.

In [10]:
# The output of dot product is a scalr number.

y = np.array([1,2,3])
x = np.array([20,30,40])

In [11]:
np.dot(y,x)

200

In [13]:
# Hadamard product - Element-wise multiplication of two vectors.
# The output of Hadamard product is ANOTHER VECTOR.

y = np.array([1,2,3])
x = np.array([20,30,40])

In [14]:
y * x

array([ 20,  60, 120])

## Matrix

In [15]:
a = np.array([
    [10,20,30],
    [40,50,60]
])
a.shape

(2, 3)

### Scalar Operation

In [17]:
a = np.array([
    [10,20],
    [30,40]
])
a

array([[10, 20],
       [30, 40]])

In [18]:
a + 5

array([[15, 25],
       [35, 45]])

### Element-wise Operations

In [19]:
a = np.array([
    [10,20],
    [30,40]
])

In [20]:
b = np.array([
    [10,20],
    [30,40]
])

In [21]:
a + b

array([[20, 40],
       [60, 80]])

### Multiplication

Matrix multiplication spcifies a set of rules for multipling matrices to produce a new matrix.

#### Dot Product 
       Rules: 
          1. The number of columns is the first matrix must equal the number of rows in the second.
          2. The product of an M x N matrix and N x K matrix is an M x K matrix. The new matrix takes the rows of the first and columns of the second.

In [22]:
a = np.array([
    [1,2]
])
a.shape

(1, 2)

In [24]:
b = np.array([
    [3,4],
    [5,6]
])
b.shape

(2, 2)

In [25]:
mn = np.dot(a,b)
mn

array([[13, 16]])

In [26]:
mn.shape

(1, 2)

#### Hadamard Product
Hadamard Product is an elementwise multiplication positionally corresponding values are multiplied to product a new matrix.

In [27]:
a = np.array([
    [20,30],
    [20,30]
])

b = np.array([
    [30,40],
    [50,60]
])

In [28]:
a * b

array([[ 600, 1200],
       [1000, 1800]])

You can take the Hadamard Product of a matrix and a vector as long as their dimensions are compatible.

In [29]:
# Same number of rows
a = np.array([
    [10],
    [20]
])
b = np.array([
    [30,40],
    [50,60]
])

In [31]:
a*b

array([[ 300,  400],
       [1000, 1200]])

In [32]:
# Same number of columns
c = np.array([
    [10,20]
])

In [33]:
b * c

array([[ 300,  800],
       [ 500, 1200]])